### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by KaMyKaSii** [Pmmlabs/OpenPeriscope#109]
Do you consider the possibility of making an Android version?

**Comment by Pmmlabs** [comment]
My aim was to make a desktop app, because earlier Periscope was only on mobile devices. In my mind, there is no point to build it for Android, because official app exists.
However, someone told me that it's possible to run OpenPeriscope as userscript with Tampermonkey extension for Yandex browser (it supports Chrome extensions)

**Comment by KaMyKaSii** [comment]
@Pmmlabs my goal is to get the download link easily, so an app would be very good. I downloaded Yandex Alpha, installed Tampermonkey and then your script. Unfortunately in example.net does not appear the OpenPeriscope interface, just an example page. Upon entering this site, Tampermonkey informs you that your UserScript is active. I tested other UserScripts and they worked perfectly so the problem (probably) is not with Tampermonkey. Would you help me? Thank you!

![screenshot_20180331-195223](https://user-images.githubusercontent.com/17092335/38168485-c1396e7c-3523-11e8-8114-2aa4815ff9dc.png)
![screenshot_20180331-195228](https://user-images.githubusercontent.com/17092335/38168487-c92e41a2-3523-11e8-9329-a67e2673e19c.png)
